# Generated by Django 3.2.18 on 2023-04-26 14:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_FieldTask',
            fields=[
                ('filedtask_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_destination', models.CharField(blank=True, max_length=500, null=True)),
                ('end_destination', models.CharField(blank=True, max_length=500, null=True)),
                ('total_km', models.CharField(blank=True, max_length=500, null=True)),
                ('from_dest', models.CharField(blank=True, max_length=500, null=True)),
                ('to_dest', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_FieldTask_Purpose_Master',
            fields=[
                ('fieldtask_purpose_master_id', models.AutoField(primary_key=True, serialize=False)),
                ('purpose', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_System_Config',
            fields=[
                ('system_config_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_task_after_min', models.BigIntegerField(blank=True, null=True)),
                ('task_deadline_min', models.BigIntegerField(blank=True, null=True)),
                ('reward_amount', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_TaskTemplate',
            fields=[
                ('task_template_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('est_min', models.PositiveBigIntegerField(blank=True, null=True)),
                ('template_status', models.CharField(blank=True, choices=[('Approve', 'Approve'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=50, null=True)),
                ('priority', models.CharField(blank=True, choices=[('Highest', 'Highest'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Lowest', 'Lowest')], default='Medium', max_length=30, null=True)),
                ('is_fieldtask', models.BooleanField(default=False)),
                ('show_for_all', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_Tasks',
            fields=[
                ('tasks_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_title', models.CharField(blank=True, max_length=500, null=True)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, choices=[('Highest', 'Highest'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Lowest', 'Lowest')], default='Medium', max_length=30, null=True)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2023, 4, 28, 14, 11, 54, 536201, tzinfo=utc))),
                ('in_desktop_crm', models.BooleanField(default=False)),
                ('est_min', models.PositiveBigIntegerField(blank=True, null=True)),
                ('remind_before_min', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('user_deadline', models.DateTimeField(blank=True, null=True)),
                ('approval_deadline', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, choices=[('', '-Select'), ('Lead', 'Lead'), ('Customer', 'Customer'), ('Employee', 'Employee'), ('Other', 'Other')], default='Other', max_length=100, null=True)),
                ('source_id', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('doc_approval', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('', '-Select'), ('All', 'All'), ('Active', 'Active'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Active', max_length=100)),
                ('rejected_note', models.CharField(blank=True, max_length=500, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('otp', models.PositiveBigIntegerField(blank=True, null=True)),
                ('otp_date', models.DateTimeField(blank=True, null=True)),
                ('spend_min', models.PositiveBigIntegerField(blank=True, null=True)),
                ('completed_percentage', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('is_field_task', models.BooleanField(default=False)),
                ('is_recurring_task', models.BooleanField(default=False)),
                ('recurring_type', models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('Weekly', 'Weekly'), ('custom', 'custom')], max_length=100, null=True)),
                ('filedtask_id', models.ManyToManyField(blank=True, to='app_system.Tbl_FieldTask')),
                ('task_template_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_system.tbl_tasktemplate')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_fieldtask',
            name='fieldtask_purpose_master_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_system.tbl_fieldtask_purpose_master'),
        ),
    ]
